export default {
    site: 'http://localhost:8080',
    // SPA: use the browser to discover content, not raw HTML
    scanner: {
        device: 'desktop',
        // Disable sitemap/robots discovery — this is a client-rendered SPA
        sitemap: false,
        robotsTxt: false,
        // Seed with all known routes since the crawler can't discover them from static HTML
        samples: 1,
    },
    // Only run accessibility audits
    lighthouse: {
        categories: ['accessibility'],
    },
    urls: [
        '/',
        '/docs/getting-started',
        '/docs/components',
        '/docs/components/accessible-icon',
        '/docs/components/accordion',
        '/docs/components/alert-dialog',
        '/docs/components/aspect-ratio',
        '/docs/components/avatar',
        '/docs/components/calendar',
        '/docs/components/checkbox',
        '/docs/components/collapsible',
        '/docs/components/combobox',
        '/docs/components/context-menu',
        '/docs/components/dialog',
        '/docs/components/dropdown-menu',
        '/docs/components/form',
        '/docs/components/hover-card',
        '/docs/components/label',
        '/docs/components/menu',
        '/docs/components/menubar',
        '/docs/components/navigation-menu',
        '/docs/components/otp-field',
        '/docs/components/password-toggle-field',
        '/docs/components/popover',
        '/docs/components/progress',
        '/docs/components/radio-group',
        '/docs/components/scroll-area',
        '/docs/components/select',
        '/docs/components/separator',
        '/docs/components/slider',
        '/docs/components/switch',
        '/docs/components/tabs',
        '/docs/components/time-field',
        '/docs/components/toast',
        '/docs/components/toggle',
        '/docs/components/toggle-group',
        '/docs/components/toolbar',
        '/docs/components/tooltip',
    ],
}
